services:
  server:
    build: ./server
    networks: [frog-net]
    env_file: ./server/.env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=${VITE_API_URL}
    networks: [frog-net]
    env_file: ./client/.env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
networks:
  frog-net:
